In [1]:
# ipynb形式のライブラリのインポート
%run ./lib.ipynb

In [2]:
def return_dict_summary_fixed(benchmark_name="cg", fixed="class"):
    if (fixed == "class"):
        fixed_ = return_fixed_class(BenchMark=benchmark_name)
    else:
        fixed_ = return_fixed_process(BenchMark=benchmark_name)
    summary_fixed_ = pd.concat(fixed_ , axis=1)
    columns = summary_fixed_.columns.to_numpy()
    index = summary_fixed_.index.to_numpy()
    if(fixed == "class"):
        dict_summary_fixed_ = {"processes":columns}
    else:
        dict_summary_fixed_ = {"class":columns}
    for index_name in index:
        dict_summary_fixed_[index_name] = summary_fixed_.T[index_name].to_numpy()
    return dict_summary_fixed_

In [4]:
for benchmark in benchmarks:
    dict_summary_fixed_class = return_dict_summary_fixed(benchmark_name=benchmark, fixed="class")
    raw_x = dict_summary_fixed_class["processes"]
    print(raw_x)
    for content in dict_summary_fixed_class:
        print(raw_y)
        raw_y = dict_summary_fixed_class[content]
        # 線形モデル
        model_lin = ModelLin(raw_x, raw_y, benchmark, content)
        model_lin.calc_lr()
        model_lin.calc_r2_score()
        # logモデル
        model_log10 = ModelLog10(raw_x, raw_y, benchmark, content)
        model_log10.calc_lr()
        model_log10.calc_r2_score()
        # 反比例モデル
        model_ip = ModelIP(raw_x, raw_y, benchmark, content)
        model_ip.calc_lr()
        model_ip.calc_r2_score()
        
        
        print(content)
    print("\n")

[  2   4   8  16  32  64 128 256]
[ 1. nan  1. nan nan nan  1. nan]
processes
[  2   4   8  16  32  64 128 256]
.TAU_application
[1. 1. 1. 1. 1. 1. 1. 1.]
MPBT
[1. 1. 1. 1. 1. 1. 1. 1.]


ValueError: Input contains NaN, infinity or a value too large for dtype('float64').