In [1]:
# ipynb形式のライブラリのインポート
%run ./lib/lib.ipynb

# 生データの入ったCSVファイルの保持されたディレクトリ名を格納している変数
csvDirPath = "./csv_files/"
benchmarkNames = ["cg", "ep", "ft", "is", "lu", "mg"]

DEBUG:__main__:hello


In [2]:
# ipynb形式のライブラリノートを.py形式に変更したものをインポート
import lib
import lib.lab_lib
from lib.lab_lib import *

DEBUG:lib.lab_lib:hello


In [3]:
benchmark_name = "cg"

classes = ["A", "B", "C", "D", "E", "F"]
processes = [2, 4, 8, 16, 32, 64, 128, 256]

dict_column_names_JP = {
    "functionName": "関数名",
    "modelLin": "線形",
    "modelIp": "反比例",
    "modelLog": "対数",
    "modelLinAndIp": "線形＆反比例",
    "modelLinAndLog": "線形＆対数",
    "modelIpAndLin": "反比例＆線形",
    "modelIpAndLog": "反比例＆対数",
    "modelLogAndLin": "対数＆線形",
    "modelLogAndIp": "対数＆反比例",
}

model_names_list_JP = list(dict_column_names_JP.values())
model_names_list_JP.remove("関数名")

model_names_list = list(dict_column_names_JP.keys())
model_names_list.remove("functionName")

date = "2022年2月2日"

# コア数と問題サイズの両方を振る

rawDF = return_rawDF_with_init_param(
    benchmark_name=benchmark_name,
    classes=classes,
    processes=processes,
    csv_dir_path="./csv_files/",
)

exp_var = rawDF.columns.tolist()
for element_be_removed in [
    "functionName",
    "functionCallNum",
    "intBenchmarkClass",
    "benchmarkName",
    "benchmarkClass",
]:
    exp_var.remove(element_be_removed)
res_var = ["functionCallNum"]

rawDF_CONJ_GRAD = rawDF[rawDF["functionName"] == "CONJ_GRAD"]
rawDF_CONJ_GRAD

# returned_MAPE_table = return_MAPE_Table_DF_from_rawDF(
#     rawDF=rawDF,
#     exp_var_list=exp_var,
#     res_var_list=res_var,
#     model_name_list=model_names_list,
# )
# df = returned_MAPE_table.rename(columns=dict_column_names_JP)
# df = df.set_index("関数名")
# df = df.sort_index(axis=0)
# df = df.sort_index(axis=1)

# df = addLowestMAPEsModelNameColumn(df, version=2, model_name_list=model_names_list_JP)

# print(
#     df.to_latex(
#         caption=f"ベンチマークプログラム{benchmark_name.upper()}における各モデルでのMAPE",
#         label=f"{date}everyModelsMAPEtableIn{benchmark_name.upper()}",
#     )
# )

functionName  functionCallNum benchmarkName benchmarkClass  process  \
5    CONJ_GRAD             16.0            cg              A        2   
5    CONJ_GRAD             16.0            cg              A        4   
5    CONJ_GRAD             16.0            cg              A        8   
5    CONJ_GRAD             16.0            cg              A       16   
5    CONJ_GRAD             16.0            cg              A       32   
5    CONJ_GRAD             16.0            cg              A       64   
5    CONJ_GRAD             16.0            cg              A      128   
6    CONJ_GRAD             16.0            cg              A      256   
2    CONJ_GRAD             31.0            cg              B        2   
2    CONJ_GRAD             46.0            cg              B        4   
2    CONJ_GRAD             76.0            cg              B        8   
2    CONJ_GRAD             76.0            cg              B       16   
2    CONJ_GRAD             76.0            cg              B       32   
2    CONJ_GRAD             76.0            cg              B       64   
2    CONJ_GRAD             76.0            cg              B      128   
2    CONJ_GRAD             76.0            cg              B      256   
2    CONJ_GRAD             76.0            cg              C        2   
2    CONJ_GRAD             76.0            cg              C        4   
2    CONJ_GRAD             76.0            cg              C        8   
2    CONJ_GRAD             76.0            cg              C       16   
2    CONJ_GRAD             76.0            cg              C       32   
2    CONJ_GRAD             76.0            cg              C       64   
2    CONJ_GRAD             76.0            cg              C      128   
2    CONJ_GRAD             76.0            cg              C      256   
2    CONJ_GRAD             76.0            cg              D        2   
2    CONJ_GRAD             76.0            cg              D        4   
2    CONJ_GRAD             76.0            cg              D        8   
2    CONJ_GRAD            101.0            cg              D       16   
2    CONJ_GRAD            101.0            cg              D       32   
2    CONJ_GRAD            101.0            cg              D       64   
2    CONJ_GRAD            101.0            cg              D      128   
2    CONJ_GRAD            101.0            cg              D      256   
2    CONJ_GRAD            101.0            cg              E       32   
2    CONJ_GRAD            101.0            cg              E       64   
2    CONJ_GRAD            101.0            cg              E      128   
2    CONJ_GRAD            101.0            cg              E      256   
2    CONJ_GRAD            101.0            cg              F      256   

   intBenchmarkClass        na  nonzer  niter  shift  
5                  1     14000      11     15     20  
5                  1     14000      11     15     20  
5                  1     14000      11     15     20  
5                  1     14000      11     15     20  
5                  1     14000      11     15     20  
5                  1     14000      11     15     20  
5                  1     14000      11     15     20  
6                  1     14000      11     15     20  
2                  4     75000      13     75     60  
2                  4     75000      13     75     60  
2                  4     75000      13     75     60  
2                  4     75000      13     75     60  
2                  4     75000      13     75     60  
2                  4     75000      13     75     60  
2                  4     75000      13     75     60  
2                  4     75000      13     75     60  
2                 16    150000      15     75    110  
2                 16    150000      15     75    110  
2                 16    150000      15     75    110  
2                 16    150000      15     75    110  
2                 16    150000      15     75    110  
2                

# （2022年2月23日～）

# 新モデルの実装

In [4]:
# TODO:新モデルに変更する


class Model_ProcessesDevidedByProblemSize_ForMultipleRegression(
    ModelBaseForMultipleRegression
):
    """プロセス数を問題サイズの変数群の線形和で割ったモデル

    組み合わせモデルを実現するためのクラス

    Attributes:
        equationDict (dict): キー・バリューが列名・変形モデル（線形、反比例、対数など）
        lr : モデルのオブジェクト
        dataXForPredict : 説明変数のDF
        dataTForPredict : 目的変数のDF
    Note:
        モデルの式は次の通り
        関数コール回数 = (プロセス数)/(a * 問題サイズ1 + b * 問題サイズ2 + ... + n * 問題サイズn + c)
    """


    
    def build_model(self):
        """build_model(self)

        inputDFのデータからモデル構築する。

        Args:
            self : none

        Returns:
        """
        
        self.len_list_coefficient = 5
        
        # TODO:curve_fit()
        

        print(f"self.rawExplanaoryVariable\n{self.rawExplanaoryVariable}")
        print(f"self.rawResponseVariable\n{self.rawResponseVariable}")
        
        # list_expをlist_inputとし利用
        list_exp = self.rawExplanaoryVariable.to_numpy().T
        print(list_exp)
        
        # 説明変数(=len(list_exp))の個数が{self.len_list_coefficient}より大きい(={self.len_list_coefficient}+1以上)なら警告を出す
        if len(list_exp) > self.len_list_coefficient:
            warnings.warn(f"説明変数の個数が想定({self.len_list_coefficient})より大きいです（len(list_exp)={len(list_exp)}）")
        # list_exp(=list_input) の0埋めをする
        if len(list_exp) < self.len_list_coefficient:
            print(f"list_exp.shape() = {list_exp.shape}")
            # while( len(list_exp) != self.len_list_coefficient ):
                
        # モデルの構築
        
        # 作成したモデルをアトリビュートに入れる。

    def predict(self, inputDF):
        """predict(self, inputDF)

        inputDFのデータから構築されたモデルを使って予測を行う

        Args:
            self : none
            inputDF (pandas.DataFrame): 構築されたモデルを用いて予測に使うDF

        Returns:
            pandas.DataFrame: 構築されたモデルから予測された値。型に確証なし
        """
        
        # TODO:predict()を必要に応じて実装する
        

    def returnMAPE(self):
        """calcMAPE(self)

        モデルの構築に使用されたデータからMAPEを算出する

        Args:
            self : none

        Returns:
            list: モデルの構築に用いたデータから予測された値
            int: 失敗した場合、-1
        """

        # TODO:returnMAPE()を必要に応じて実装する
        
# めも：list_input と coefficient_* の個数は同じにする。できない場合は0埋めをしたのを数合わせにlist_inputに入れる
# モデル式の宣言
def ProcessesDevidedByProblemSize(list_input = [], coefficient_a = 0, coefficient_b = 0, coefficient_c = 0, coefficient_d = 0, coefficient_e = 0, intercept = 0):

    list_coefficient = [coefficient_a, coefficient_b, coefficient_c, coefficient_d, coefficient_e]
    # list_inputの要素数と有効なa,b,c,d,eの個数が同じことを確認
    if len(list_input) != len(list_coefficient):
        warnings.warn(f"len(list_input){len(list_input)} != len(list_coefficient){len(list_coefficient)}")
    int_list_length = len(list_input)
    # 分子(numerator)の計算
    numerator = list_input[0] * coefficient_a

    # 分母(denominator)の計算
    list_input_denominator = np.array(list_input)
    list_input_denominator = list_input_denominator.reshape([len(list_input_denominator), -1]).T
    list_coefficient_denominator = np.array(list_coefficient)
    list_coefficient_denominator = list_coefficient_denominator.reshape([1, len(list_coefficient_denominator)])
    denominator = np.inner(list_input_denominator, list_coefficient_denominator)
    denominator.revel()

    # 返す値の計算 ( = 分子/分母 + 切片)
    result = numerator / denominator + intercept

def test_Model_ProcessesDevidedByProblemSize_ForMultipleRegression():
    """test_ModelMultipleEquationForMultipleRegression()

    ModelMultipleEquationForMultipleRegressionのテスト
    """

    # 説明変数
    plotX = np.linspace(10, 20, 11)
    plotY = np.linspace(20, 30, 11)
    plotZ = np.linspace(30, 40, 11)
    # 目的変数
    a = random.uniform(1, 30)
    b = random.uniform(1, 30)
    c = random.uniform(1, 30)
    d = random.uniform(1, 30)
    plotT = (a * plotX) / (b * plotY + c * plotZ) + d

    # DFを作成する
    # カラム名のリスト
    columnNames = ["plotX", "plotY", "plotZ", "plotT"]
    datumForDF = [plotX, plotY, plotZ, plotT]
    inputDFForTest = pd.DataFrame(index=columnNames, data=datumForDF).T
    inputDFForTest["functionName"] = "functionName"

    # 目的変数・説明変数のカラム名のリスト
    # 目的変数のカラム名のリスト
    columnNamesForExp = ["plotX", "plotY", "plotZ"]
    # 説明変数のカラム名のリスト
    columnNamesForRes = ["plotT"]

    # 予測をする
    # モデルオブジェクトの作成
    objectModel = Model_ProcessesDevidedByProblemSize_ForMultipleRegression(
        inputDF=inputDFForTest,
        explanatoryVariableColumnNames=columnNamesForExp,
        responseVariableColumnNames=columnNamesForRes,
        conditionDictForTest={},
    )
    # TODO:モデルの構築
    objectModel.build_model()
    # モデル構築に用いたデータとのMAPEによって実装がうまくいっているかどうかの判定を行う
    MAPE = objectModel.returnMAPE()
    print(f"MAPE = {MAPE}")
    assert MAPE < 1

In [5]:
test_Model_ProcessesDevidedByProblemSize_ForMultipleRegression()

self.rawExplanaoryVariable
    plotX  plotY  plotZ
0    10.0   20.0   30.0
1    11.0   21.0   31.0
2    12.0   22.0   32.0
3    13.0   23.0   33.0
4    14.0   24.0   34.0
5    15.0   25.0   35.0
6    16.0   26.0   36.0
7    17.0   27.0   37.0
8    18.0   28.0   38.0
9    19.0   29.0   39.0
10   20.0   30.0   40.0
self.rawResponseVariable
        plotT
0   10.936393
1   10.956194
2   10.974555
3   10.991625
4   11.007537
5   11.022405
6   11.036328
7   11.049393
8   11.061678
9   11.073250
10  11.084169
[[10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
 [20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]
 [30. 31. 32. 33. 34. 35. 36. 37. 38. 39. 40.]]
list_exp.shape() = (3, 11)
MAPE = None


TypeError: '<' not supported between instances of 'NoneType' and 'int'

# （2022年2月22日～）【個人作業】

# 回帰木による予測

In [ ]:
from sklearn.tree import DecisionTreeRegressor

rawDF

In [ ]:
rawDF_CONJ_GRAD = rawDF[rawDF["functionName"] == "CONJ_GRAD"]
rawDF_CONJ_GRAD

In [ ]:
print(f"exp_var = {exp_var}")

print(f"res_var = {res_var}")

print(f"rawDF_CONJ_GRAD.shape = {rawDF_CONJ_GRAD.shape}")

In [ ]:
X = rawDF_CONJ_GRAD.filter(items=exp_var)
Y = rawDF_CONJ_GRAD.filter(items=res_var)

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.1, random_state=1234
)

# X_train, X_test, Y_train, Y_test

In [ ]:
reg = DecisionTreeRegressor(max_leaf_nodes=20)

model = reg.fit(X_train, Y_train)
print(f"model = {model}")

In [ ]:
from sklearn.metrics import r2_score

YHat = model.predict(X_test)
r2 = r2_score(Y_test, YHat)
print("R^2 = ", r2)

In [ ]:
from sklearn import tree
from IPython.display import Image
import pydotplus

dot_data = tree.export_graphviz(
    model,
    out_file=None,
    feature_names=rawDF_CONJ_GRAD.feature_names,
    class_names="functionCallNum",
    filled=True,
)
graph = pydotplus.graph_from_dot_data(dot_data)

Image(graph.create_png())